name: Build&Test

on:
  push:
    branches: [ "v1.1.0" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build UiIndependent
      run: dotnet build src/EnkuToolkit.UiIndependent/EnkuToolkit.UiIndependent.csproj -C $env:Configuration

    - name: Build Wpf
      run: dotnet build src/EnkuToolkit.Wpf.Test/EnkuToolkit.Wpf.csproj -C $env:Configuration

    - name: Test UiIndependent
      run: dotnet test src/EnkuToolkit.UiIndependent.Test/EnkuToolkit.UiIndependent.Test.csproj -C $env:Configuration
