name: Docs

on:
  push:
    branches: [ "v1.1.0" ]
  pull_request:
    branches: [ "main" ]

jobs:
  publish-docs:
    runs-on: windows-latest
    
    steps:
    - name: Chekout
      uses: actions/checkout@v3

    - name: Dotnet Setup
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build UiIndependent
      run: dotnet build src/EnkuToolkit.UiIndependent/EnkuToolkit.UiIndependent.csproj -c Release

    - name: Build Wpf
      run: dotnet build src/EnkuToolkit.Wpf/EnkuToolkit.Wpf.csproj -c Release

    - run: dotnet tool update -g docfx

    - run: docfx docfx.json

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_site