name: PublishDocs

on:
  push:
    branches: [ "v1.1.0" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build UiIndependent
      run: dotnet build src/EnkuToolkit.UiIndependent/EnkuToolkit.UiIndependent.csproj -c Release

    - name: Build Wpf
      run: dotnet build src/EnkuToolkit.Wpf/EnkuToolkit.Wpf.csproj -c Release

    - run: dotnet tool update -g docfx

    - run: docfx docfx.json

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
    
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2